<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TihorFruzsina_orarend [
    <!ELEMENT TihorFruzsina_orarend (ora+)>
    <!ELEMENT ora (targy, idopont, helyszin, oktato | oraado, szak)>
        <!ELEMENT targy (#PCDATA)>
        <!ELEMENT idopont (nap, tol, ig)>
            <!ELEMENT nap (#PCDATA)>
            <!ELEMENT tol (#PCDATA)>
            <!ELEMENT ig (#PCDATA)>
        <!ELEMENT helyszin (#PCDATA)>
        <!ELEMENT oktato (#PCDATA)>
        <!ELEMENT oraado (#PCDATA)>
        <!ELEMENT szak (#PCDATA)>
    <!ATTLIST ora id ID #REQUIRED
                  típus (előadás|gyakorlat) #REQUIRED>
]>
<TihorFruzsina_orarend>
    <ora id="1" típus="elmélet">
        <targy>Szoftvertesztelés</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>8:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oraado>Dr. Hornyák Olivér</oraado>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="2" típus="gyakorlat">
        <targy>Szoftvertesztelés</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Hornyák Olivér</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="3" típus="elmélet">
        <targy>WEB technológiák</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>XXX ea</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="4" típus="gyakorlat">
        <targy>WEB technológiák</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="5" típus="elmélet">
        <targy>Mesterséges intelligencia</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>XXXII ea</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="6" típus="elmélet">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>XXXII ea</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="7" típus="elmélet">
        <targy>WEB-es alkalmazások Java</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>Teams</helyszin>
        <oktato>EPAM</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="8" típus="gyakorlat">
        <targy>WEB-es alkalmazások Java</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>Teams</helyszin>
        <oktato>EPAM</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="9" típus="elmélet">
        <targy>Integrált vállalati rendszerek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>X ea</helyszin>
        <oktato>Dr. Dadvandipour Samad</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="10" típus="gyakorlat">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="11" típus="gyakorlat">
        <targy>Integrált vállalati rendszerek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>Inf/15</helyszin>
        <oktato>Kulcsárné Dr. Forrai Mónika</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
    <ora id="12" típus="gyakorlat">
        <targy>Mesterséges intelligencia</targy>
        <idopont>
            <nap>csütörtök</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>I A2 fsz</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Mérnökinformatikus</szak>
    </ora>
</TihorFruzsina_orarend>
